#!/usr/bin/env bash
# Transfers a file from our client to a server
if [ "$4" ]; then
    scp "$1" -i "$4" "$3@$2:~"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed"
fi
