#!/usr/bin/env bash
# Redirect an endpoint to another page

apt-get update
apt-get -y install nginx
new="server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        location / {
                try_files $uri $uri/ =404;
                error_page 404 @sorry;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location @sorry {
                return 404 'Ceci n'est pas une page';
        }
}"
echo "$new" > /etc/nginx/sites-available/default
service nginx stop
service nginx start
