#!/usr/bin/env bash
# Print out IP of various A records

get_ip() {
    ip=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{ print $5 }' | tr -d '\n')
    r=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{ print $4 }' | tr -d '\n')
    echo "The subdomain $2 is a $r record and points to $ip"
}

if [ "$2" ]; then
    full_domain="$2.$1"
    get_ip "$full_domain" "$2"
else
    get_ip "www.$1" "www"
    get_ip "lb-01.$1" "lb-01"
    get_ip "web-01.$1" "web-01"
    get_ip "web-02.$1" "web-02"
fi
