#!/usr/bin/env bash
# Create custom HTTP header

sudo apt-get update
sudo apt-get -y install nginx
TEXT="add_header X-Served-By $HOSTNAME;"
sudo sed -i "32i $TEXT" /etc/nginx/sites-available/default
sudo service nginx restart
