#!/usr/bin/env bash
# Installs HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo 'ENABLED=1' | sudo tee /etc/default/haproxy
sudo sed -i "1 i\listen appname\n\tbind 0.0.0.0:80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?stats\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 139-web-01 142.44.167.246:80 check\n\tserver 139-web-02 144.217.246.220:80 check\n" /etc/haproxy/haproxy.cfg
sudo sed -i '/global/,$d' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
