#!/usr/bin/env bash
# Does a plethora of tasks

quit()
{
    rm /var/run/holbertonscript.pid
    kill -SIGKILL $$
}

terminate()
{
    echo "I hate the kill command"
    quit
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'terminate' SIGTERM
trap 'quit' SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while true; do
    echo "To infinity and beyond"
    sleep 2
done
