#!/usr/bin/env bash
# Does a plethora of tasks

terminate()
{
    echo "I hate the kill command"
}

quit()
{
    terminate
    rm /var/run/holbertonscript.pid
}

trap 'terminate' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'quit' SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while [ true ]; do
    echo "To infinity and beyond"
    sleep 2
done
