#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times & "Hi" once

i=0

while [ "$i" -lt 10 ]
do
    if [ "$i" -eq 8 ]; then
	echo "Hi"
    else
	echo "Holberton School"
    fi
    let "i += 1"
done
