#!/usr/bin/env bash
# This script is displaying a clock

hours=0
minutes=1

while [ "$hours" -le 12 ]
do
    echo "Hour: $hours"
    while [ "$minutes" -lt 60 ]
    do
	echo "$minutes"
	let "minutes += 1"
    done
    let "hours += 1"
    let "minutes = 1"
done
