#!/usr/bin/env bash
# Gives you information about the holbertonschool file

le_file="holbertonschool"
if [ -e "$le_file" ]; then
    echo "holbertonschool file exists"
    if [ -s "$le_file" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$le_file" ]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
